### PR TITLE
feat: add tfsec-checkgen test-check command to test custom check against tf test code

### PR DESCRIPTION
**Pull request by gabrielleecredera**
- new command `tfsec-checktest test-check <custom_check_file> -p <pass.tf> -f <fail.tf>`
- number of `--pass`/`-p`/`--fail`/`-f` flags are optional and variable
- had to modify the internal custom package to expose functions
- subcommand `test-check` used to prep for future `test-checks` command that runs tests against more than one custom check files

partially solves #1415

### CODE REVIEW

**Comment by owenrumney** [comment]
Could this be added as an additional command to tfsec-checkgen?

**Comment by gabrielleecredera** [comment]
I added it as a new command as I think I've seen somewhere that the original purpose of checkgen is to generate custom checks? I'm not sure if that vision is still true tho, let me know if adding it into checkgen is preferred. :)

**Comment by owenrumney** [comment]
> I added it as a new command as I think I've seen somewhere that the original purpose of checkgen is to generate custom checks? I'm not sure if that vision is still true tho, let me know if adding it into checkgen is preferred. :) (unrelated: if the vision is still true, what's the solution expected to look like? some cli q&a to generate a custom check file?)

Yeah, lets stick with it being part of checkgen since its all the same sort of thing.

In answer to the other question, before we moved to defsec we had tfsec-skeleton which asked you a number of questions about services, required labels, required resources. I think it would do similar to that.... I think there is only so far we can go with automating the generation of custom checks so it will be a bit trial and error

**Review by owenrumney — APPROVED** [review]
Thanks again @gabrielleecredera  - your contributions are really appreciated :heart:

**Comment by owenrumney** [comment]
hey @gabrielleecredera  - looks like a goimports issue breaking the build

**Review by owenrumney — APPROVED** [review]

**Pull request merged**
