### PR TITLE
DigitalOcean Buckets/Spaces, firewalls and load balancers

### PR DESCRIPTION
**Pull request by atombrella**
(All) the tests fail, and some assistance is appreciated. Probably the code can be simplified and tidied up a bit. Feel free to push to my branch; it's open to repository owners.

You can tick off the two items in #1194 that relate to Digital Ocean once this has been merged.

### CODE REVIEW

**Comment by owenrumney** [comment]
Hey @atombrella  - this is great, thanks for contributing!

Looks to me like trivial things, for example - https://github.com/aquasecurity/tfsec/pull/1246/files#diff-c1653e36b79f10d53f0fd47f68061d5e04cc0969d6778850b05f4da72b73506bR80 - the ForwardingRules aren't being added to the loadbalancer, but the load balancer is being added to the returned loadbalancers

I've made a tweak below which fixes that particular issue.

```go
func adaptLoadBalancers(module block.Modules) (loadBalancers []compute.LoadBalancer) {

	for _, block := range module.GetResourcesByType("digitalocean_loadbalancer") {
		forwardingRules := block.GetBlocks("forwarding_rule")
		fRules := []compute.ForwardingRule{}

		for _, fRule := range forwardingRules {
			rule := compute.ForwardingRule{}
			rule.EntryProtocol = fRule.GetAttribute("entry_protocol").AsStringValueOrDefault("", fRule)
			fRules = append(fRules, rule)
		}
		loadBalancers = append(loadBalancers, compute.LoadBalancer{
			ForwardingRules: fRules,
		})
	}

	return loadBalancers
}
```

**Comment by owenrumney** [comment]
Hey @atombrella  - happy to make the changes to the branch if you want, I was assuming you'd want a hint at the issue. I'm easy either way - we just really appreciate the contributions :+1:

**Comment by atombrella** [comment]
I fixed the spaces tests :tada: However, I'm not really sure what I'm doing wrong with the firewall adapters, as those tests fail.

**Comment by liamg** [comment]
@atombrella Cool, nice one, I'll take a quick look at the firewall issue.

**Review by owenrumney — APPROVED** [review]

**Comment by liamg** [comment]
@atombrella the remaining issues were all entirely my own fault, so I've pushed fixes accordingly. Thanks for your perseverance!

**Pull request merged**
