### PR TITLE
Fix various linting errors.

### PR DESCRIPTION
**Pull request by atombrella**
I'm a bit new to GoLang (picking it up by contributing a bit to Terraform providers). I experimented with https://golangci.com/ where this came up. There are many other checks, e.g.,

```
internal/app/tfsec/security/sensitive.go:19:5: `sensitiveAttributes` is unused (deadcode)
var sensitiveAttributes = map[string]string{}
```

### CODE REVIEW

**Review by owenrumney — APPROVED** [review]
Nice, thanks @atombrella  - amazing how much crap gets left behind that you don't notice.

**Comment by owenrumney** [comment]
@atombrella  - hope you're enjoying Go, thanks for the contribution. 

Could you could you sign our CLA https://cla-assistant.io/aquasecurity/tfsec?pullRequest=1198 so we can accept the PR. It's nothing onerous, just a requirement of Aqua security for OSS projects

**Comment by atombrella** [comment]
Signed. I'd suggest adding a linting step to the workflow, to avoid introducing more :) I just copied the [.golangci](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/.golangci.yml) into the repository, and ran the linters. There are loads more than the ones they enabled, but I'm unsure which are useful and which that aren't.

**Comment by atombrella** [comment]
https://go-critic.com/overview.html finds the most.

**Pull request merged**
