### PR TITLE
Use set instead of shebang in install_linux.sh

### PR DESCRIPTION
**Pull request by ddelange**
`curl install_linux.sh | bash` does not respect the shebang

see also https://github.com/terraform-linters/tflint/pull/1870

### CODE REVIEW

**Comment by ddelange** [comment]
cc @simar7

**Comment by ddelange** [comment]
[http.cat/204](https://http.cat/204)

**Comment by ddelange** [comment]
ping @simar7

**Comment by ddelange** [comment]
ping

**Comment by ddelange** [comment]
ping @simar7

**Comment by ddelange** [comment]
ping

**Comment by ddelange** [comment]
@simar7

**Comment by ddelange** [comment]
ping

**Comment by ddelange** [comment]
ping

**Comment by reedloden** [comment]
@ddelange tfsec is dead. See https://github.com/aquasecurity/tfsec/discussions/1994.

**Comment by ddelange** [comment]
thanks for the ping. maybe archive this repo then?

**Pull request closed without merging**
