### PR TITLE
fix: fix doc link

### LINKED ISSUE #1429: bug: broken doc links in v1.0.0 release
**Describe the bug**
links to violation docs contain an extra `v` before `v1.0.0`.

```console
$ tfsec .
# snip ...
  More Information
  - https://aquasecurity.github.io/tfsec/vv1.0.0/checks/aws/dynamodb/table-customer-key/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#server_side_encryption
```

I think this is related to:

- https://github.com/aquasecurity/tfsec/pull/1397

### PR DESCRIPTION
**Pull request by owenrumney**
Resolves #1429

### CODE REVIEW

**Comment by liamg** [comment]
I think there's an issue somewhere else where we generate the docs as I had to add that `v` the other day to fix links from the CLI output

**Comment by owenrumney** [comment]
> I think there's an issue somewhere else where we generate the docs as I had to add that `v` the other day to fix links from the CLI output

This is the CLI links. Think the issue being fixed was the latest version wasn't it?

**Comment by liamg** [comment]
It was the `v` but i have no idea how that's possible :S https://github.com/aquasecurity/tfsec/issues/1395

**Comment by owenrumney** [comment]
> It was the `v` but i have no idea how that's possible :S https://github.com/aquasecurity/tfsec/issues/1395

Checked the goreleaser docs, pre release versions have the v stripped on pre release docs.

We use {{. Version}} in the golreaser manifest so I think we should play about with using {{.Tag}} longer term

But short term this fixes the issue

**Review by liamg — APPROVED** [review]

**Comment by liamg** [comment]
@owenrumney Cool, time for 1.0.1 then - was hoping 1.0.0 would last a while :D

**Comment by sergei-ivanov** [comment]
I think this change broke it again with the same effect as reported in #1395

TFsec output:
```
          ID aws-s3-specify-public-access-block
      Impact Public access policies may be applied to sensitive data buckets
  Resolution Define a aws_s3_bucket_public_access_block for the given bucket to control public access policies

  More Information
  - https://aquasecurity.github.io/tfsec/1.0.1/checks/aws/s3/specify-public-access-block/
  - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_public_access_block#bucket
```

The URL above returns 404.
The published URL has `v` in the version:
```
https://aquasecurity.github.io/tfsec/v1.0.1/checks/aws/s3/specify-public-access-block/
```

Environment:
```
$ uname -sm
Linux x86_64

$ tfsec --version
1.0.1
```

**Comment by owenrumney** [comment]
this is fixed now - thanks @sergei-ivanov

**Pull request merged**
